### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by rcsmit** [TNO/knowledge-engine#563]
FYI: code review op https://www.youtube.com/watch?v=qeZ2tPgdess

**Comment by JackJackie** [comment]
Thx Rene for your attention! We'll review the review and see what we can improve!

**Comment by rcsmit** [comment]
Hi, it's not me who did the video :) All the best :)

**Comment by bnouwt** [comment]
Some suggested improvements mentioned in above video:

- [ ] - move certain dependencies (such as logging) to dependencies management section of parent module.
- [ ] - add architectural figure with dependencies between components.
- [ ] - [extend description](https://github.com/TNO/knowledge-engine?tab=readme-ov-file#components) of different Maven modules.
- [ ] - add static analysis reporting tool to CI/CD
- [ ] - mention code convention in `/ide` folder in [developer info](https://github.com/TNO/knowledge-engine?tab=readme-ov-file#developer-information).

**Comment by bnouwt** [comment]
Moved the following dependencies to the dependency management section of the parent pom:
- slf4j-simple dependency
- junit dependencies
- jetty, jersey3, jackson dependencies

Added code convention and missing components to `README.md` and refer to the high-level design of the smart connector.

Ran one-time static analysis reporting tool locally following (partly) [this guide](https://medium.com/@anshumaansingh10jan/setting-up-sonarqube-for-code-quality-inspection-on-java-maven-gradle-net-python-go-projects-5782c17dd64f). And also using the Eclipse SonarQube plugin. The results were quite good, although of course a lot of improvements can still be done. Doing static code analysis more consistently during CI/CD is part of issue #361.
